### ISSUE TITLE
/usr/share/postgresql does not exist

### ISSUE THREAD

**Issue by TestSubject1498** [rsubr/postgres-babelfish#1]
> # Extract postgres.conf so it can be customized
> docker run -i --rm rsubr/postgres-babelfish cat /usr/share/postgresql/postgresql.conf.sample > my-postgres.conf

Just a note here-- on pulling your docker image this command from your readme fails.

The sample config is in `/usr/local/share/`
![image](https://user-images.githubusercontent.com/98116277/176188633-d739d48f-0320-48ef-96d6-2b3ede932af5.png)

There is no `/usr/share/postgresql`:
![image](https://user-images.githubusercontent.com/98116277/176189143-2dbbd20a-780a-40e9-8067-f69659cc9ae0.png)

(Your installation prefix in the dockerfile is `/usr/local/`-- which makes perfect sense)

**Comment by rsubr** [comment]
Fixed in [v1.2.0.](https://github.com/rsubr/postgres-babelfish/tree/v1.2.0).

Thanks!
